### ISSUE TITLE
Error occurred prerendering page "/tag/Cooking"...

### ISSUE THREAD

**Issue by Tan35** [yokinist/yokinist.me#3]
When I'm ready to finish deploying, there seems to be a problem during pre-rendering! It ends up not being able to complete the deployment!It's not just the error I mentioned in the title, it seems to be a problem with the search page for the tag categories when searching, I'll screenshot a few errors. Hope to get your reply! Thank you!

![image](https://user-images.githubusercontent.com/45460542/154069636-8ec4433f-e88b-48c7-81b4-6935f668c6b6.png)
![image](https://user-images.githubusercontent.com/45460542/154069684-559c762a-0fb8-49bc-a74b-2fdd52ef067b.png)

**Comment by yokinist** [comment]
Thanks for the report, I'll check later 👀

**Comment by Tan35** [comment]
> Thanks for the report, I'll check later 👀

Thank you for your help! I hope to hear from you soon

**Comment by yokinist** [comment]
@Tan35 Has the problem already been resolved?

**Comment by funcdfs** [comment]
> @Tan35 Has the problem already been resolved?

Not resolved yet. For a simple fork notion database, after modifying the pageid and starting it with vercel, there will be a phenomenon similar to the inaccessibility before the label is initialized? In the original Nobelium, as long as you modify or add or delete tags in the notion database, they will be rendered in real time in the web page, but this project seems to be a fixed value of notion tags? If it is a fixed value, where can it be modified? If it is not used in the same way as the base Nobelium repository, what is the difference. Can you let me know? (or add description in doc) thanks

**Comment by funcdfs** [comment]
> @Tan35 Has the problem already been resolved?

You can open a secondary account for testing, or use a new notion repository and a new github repository to fork, and then import it into a new vercel directory, and the above error will appear. 

The most effective way is to describe in the documentation how your tags database is used as tags for this project
