### ISSUE TITLE
ReferenceError: Cannot access 'currentTagName' before initialization

### ISSUE THREAD

**Issue by funcdfs** [yokinist/yokinist.me#4]
#3 this 
![1](https://user-images.githubusercontent.com/56250171/171686572-9214110f-5c36-480d-bd5c-dd83908a1e3c.png)

This problem still exists, emmmm... the default is too monotonous, this is good, but can't it be as easy to use as the default project?

**Comment by funcdfs** [comment]
> 

I explained it in more detail under that issue.

**Comment by El-Chiang** [comment]
Hi, I encountered the same issue while compiling this project. I found that the problem lies in this line. https://github.com/yokinist/yokinist.me/blob/e891a86e0cacfa319dfffff2f6c0687ec6fe4948/layouts/search.tsx#L32

The simplest fix is to remove the `currentTagName` at the end of this line.

**Comment by El-Chiang** [comment]
Sorry for the previous modification that caused `currentTagName` to always be `undefined`. I took a closer look at the code and found that the author defined the constant `TAG_DATA` in `lib/tags.ts` 🤔️ You can make modifications to it. 
https://github.com/yokinist/yokinist.me/blob/e891a86e0cacfa319dfffff2f6c0687ec6fe4948/lib/tags.ts#L28-L99

Alternatively, for a simpler solution, you can remove `currentTagName` altogether and directly change the [placeholder](https://github.com/yokinist/yokinist.me/blob/e891a86e0cacfa319dfffff2f6c0687ec6fe4948/layouts/search.tsx#L42) value of the input field to
``` jsx
placeholder={currentTag ? `${locale.POST.SEARCHIN} #${currentTag}` : locale.POST.SEARCH}
```

I'm not sure if the @yokinist  had any other specific purpose in defining the tag data as a constant, any better approach?

**Comment by yokinist** [comment]
@funcdfs @El-Chiang 

Sorry it took so long.

I've made the following updates:

- Adjusted the [Notion template](https://yokinist.notion.site/yokinist/761c04c4ff6e467188fe67c8a36e20b9?v=0643f1ef640642fbb84032202708336f) to match libs/tags.ts：https://github.com/yokinist/yokinist.me/commit/c24b4a50f71dbc069bc9a150494db106339a649a
- Corrected the referencing method for currentTagName : https://github.com/yokinist/yokinist.me/commit/b98c8b154cfe3a214ba27c40ecf08143b37654c9
- Added some brief clarification to the README : https://github.com/yokinist/yokinist.me/commit/f504fb744f9b0ef63e73e8c1aad0d556af1b9377

Everything should be fine now. Feel free to open an issue if needed. Thanks.

---

Preview: https://me-git-template-yokinist.vercel.app/
Notion Template: https://yokinist.notion.site/yokinist/761c04c4ff6e467188fe67c8a36e20b9?v=0643f1ef640642fbb84032202708336f
